# packages/geo-audit/analyzers/llms_generator.py
"""Detect llms.txt and generate a draft if missing.

llms.txt is an emerging standard (by Giogio Bonuchi / HTTP 421) for helping
AI systems understand a site's structure and purpose. Not yet widely adopted
but important for GEO.
"""

from urllib.parse import urljoin, urlparse

from ...crawler.models import PageRecord
from ..models import GeoIssue, GeoIssueCategory, GeoIssueSeverity


LLMS_TXT_PATHS = [
    "/llms.txt",
    "/llms-full.txt",
    "/robots.txt",  # some put llms links in robots.txt via Sitemap:
]


def analyze_llms_txt(
    llms_txt_content: str | None,
    domain: str,
    pages: list[PageRecord],
) -> list[GeoIssue]:
    """Check if llms.txt exists and assess its quality.

    Args:
        llms_txt_content: raw llms.txt content, or None if not found
        domain: site domain
        pages: all crawled pages

    Returns:
        list of GeoIssues related to llms.txt
    """
    issues: list[GeoIssue] = []

    if llms_txt_content is None:
        issues.append(
            GeoIssue(
                issue_type="llms_txt_missing",
                category=GeoIssueCategory.LLM_OUTPUT_OPTIMIZATION,
                severity=GeoIssueSeverity.MEDIUM,
                title="llms.txt not found",
                description=(
                    "No llms.txt file was found at the root of the site. "
                    "llms.txt helps AI systems (especially standalone LLM agents) "
                    "quickly understand your site's structure, purpose, and key pages "
                    "without having to crawl the entire site. "
                    "As AI search grows, this file may become important for GEO."
                ),
                recommendation=(
                    "Create an llms.txt file at the root of your site listing: "
                    "1) Site name and one-line description "
                    "2) Key site sections and their purpose "
                    "3) Contact or about page "
                    "4) Any API or data endpoints "
                    "See https://llmstxt.foeai.io/ for the spec."
                ),
                affected_element="/llms.txt",
            )
        )
    else:
        # llms.txt found — check quality
        lines = llms_txt_content.strip().splitlines()
        if len(lines) < 5:
            issues.append(
                GeoIssue(
                    issue_type="llms_txt_too_short",
                    category=GeoIssueCategory.LLM_OUTPUT_OPTIMIZATION,
                    severity=GeoIssueSeverity.LOW,
                    title="llms.txt exists but is very short",
                    description=(
                        f"llms.txt was found but only contains {len(lines)} lines. "
                        "A useful llms.txt should include the site name, description, "
                        "key sections, and important pages for AI systems to reference."
                    ),
                    recommendation=(
                        "Expand llms.txt to include: site name, tagline, key pages "
                        "(about, services, contact, blog), and a brief description of each. "
                        "Keep it scannable for AI systems."
                    ),
                    affected_element="/llms.txt",
                )
            )

    return issues


def generate_llms_txt_draft(
    domain: str,
    pages: list[PageRecord],
    site_name: str | None = None,
    site_description: str | None = None,
) -> str:
    """Generate a draft llms.txt from crawled pages.

    Args:
        domain: site domain
        pages: all crawled pages
        site_name: optional site name override
        site_description: optional site description override

    Returns:
        Draft llms.txt content as a string
    """
    lines = [
        f"# llms.txt — generated by SEO Agent OS",
        f"# Domain: {domain}",
        f"# Generated: (date)",
        "",
        "== SITE ==",
    ]

    if site_name:
        lines.append(f"Name: {site_name}")
    else:
        # Infer from first page title
        titles = [p.title for p in pages if p.title]
        site_title = titles[0].split(" | ")[0].split(" - ")[0] if titles else domain
        lines.append(f"Name: {site_title}")

    if site_description:
        lines.append(f"Description: {site_description}")
    else:
        # Infer from meta description of most-linked page
        best = max(pages, key=lambda p: p.internal_links_count, default=None)
        if best and best.meta_description:
            lines.append(f"Description: {best.meta_description}")

    lines.extend(["", "== SECTIONS =="])

    # Group pages by apparent section from URL path
    from collections import defaultdict
    sections: dict[str, list[PageRecord]] = defaultdict(list)
    for page in pages:
        parsed = urlparse(page.url)
        path_parts = [p for p in parsed.path.strip("/").split("/") if p][:2]
        section = "/".join(path_parts) or "root"
        if len(section) < 50:
            sections[section].append(page)

    # Emit top sections
    for section, section_pages in sorted(sections.items(), key=lambda x: len(x[1]), reverse=True)[:10]:
        sample = max(section_pages, key=lambda p: p.internal_links_count)
        title = sample.title or f"{section} pages"
        lines.append(f"- /{section}: {title}")

    # Key pages
    important_keywords = ["about", "contact", "services", "pricing", "blog", "faq", "help"]
    important: list[PageRecord] = []
    for page in pages:
        if not page.url:
            continue
        url_lower = page.url.lower()
        if any(k in url_lower for k in important_keywords):
            important.append(page)

    if important:
        lines.extend(["", "== IMPORTANT PAGES =="])
        seen_urls: set[str] = set()
        for page in important:
            if page.url not in seen_urls:
                seen_urls.add(page.url)
                title = page.title or page.url
                lines.append(f"- {page.url}: {title}")

    lines.extend(["", "== END =="])
    return "\n".join(lines)
